import Chat from "./chat/Chat"
import Pets from "./admin/Pets"
import Chats from "./chat/Chats"
import Terms from "./settings/Terms"
import Reports from "./admin/Reports"
import Users from "./admin/UsersList"
import Products from "./admin/Products"
import Offers from "./offers/OffersList"
import OfferNew from "./offers/OfferNew"
import Settings from "./settings/Settings"
import Password from "./settings/Password"
import Activity from "./settings/Activity"
import AdminOffers from "./admin/AdminOffers"
import Dashboard from "./dashboard/Dashboard"
import Followers from "./followers/Followers"
import Bookmarks from "./bookmarks/Bookmarks"
import CreateReport from "./report/CreateReport"
import Preferences from "./settings/Preferences"
import DeleteAccount from "./settings/DeleteAccount"
import PrivacyPolicy from "./settings/PrivacyPolicy"
import ProfileSettings from "./settings/profile/Profile"
import Notifications from "./notifications/Notifications"
import ConfigureAds from "./admin/configureAds/ConfigureAds"
import ProfileProvider from "./settings/profile/ProfileProvider"

export { Dashboard, Notifications, Offers, OfferNew, Chats, Chat, Followers, Bookmarks, Settings, ProfileSettings, ProfileProvider, Password, Preferences, Terms, PrivacyPolicy, Activity, DeleteAccount, CreateReport, Users, Reports, AdminOffers, Products, Pets, ConfigureAds }