import Chat from "./chat/Chat"
import Chats from "./chat/Chats"
import Terms from "./settings/Terms"
import About from "./settings/About"
import Offers from "./offers/OffersList"
import OfferNew from "./offers/OfferNew"
import Settings from "./settings/Settings"
import Password from "./settings/Password"
import Activity from "./settings/Activity"
import Followers from "./followers/Followers"
import ProfileSettings from "./settings/profile/Profile"
import Notifications from "./notifications/Notifications"
import ProfileProvider from "./settings/profile/ProfileProvider"

export { Notifications, Offers, OfferNew, Chats, Chat, Followers, Settings, ProfileSettings, ProfileProvider, Password, Terms, About, Activity }