import MaskInput from "./maskInput"
import TextInput from "./textInput"
import NumberInput from "./numberInput"
import SwitchInput from "./switchInput"
import PasswordInput from "./passwordInput"
import TextAreaInput from "./textAreaInput"
import DropDownInput from "./dropDownInput"
import CheckBoxInput from "./checkBoxInput"
import CalendarInput from "./calendarInput"
import FileUploadInput from "./fileUploadInput"
import RadioInput from "./radioInput/RadioInput"
import UploadPhotoInput from "./uploadPhotoInput"
import MultiSelectInput from "./multiSelectInput"

export { TextInput, RadioInput, NumberInput, SwitchInput, PasswordInput, TextAreaInput, DropDownInput, CheckBoxInput, FileUploadInput, UploadPhotoInput, MultiSelectInput, CalendarInput, MaskInput }