import home from "@assets/navBar-icons/navIcon-1.svg";

const modules = [
  {
    title: "Market Place",
    description: "Find products that are eco friendly",
    icon: home,
    hoverBackgroundColor: "#23649A",
    hoverIconColor: "#77BEF9",
    backgroundColor: "#77BEF9",
    iconBackgroundColor: "#23649A",
    height: "200px",
    fontColor: "#fff",
    link: "",
  },
  {
    title: "Recycle",
    description: "Look for recycle center companies that may interest you",
    icon: home,
    hoverBackgroundColor: "#408D27",
    hoverIconColor: "#7FAE70",
    backgroundColor: "#7FAE70",
    iconBackgroundColor: "#408D27",
    height: "200px",
    fontColor: "#fff",
    link: "",
  },
  {
    title: "Post Offer",
    description:
      "Post your recyclable material and sell it to the highest bidder",
    icon: home,
    hoverBackgroundColor: "#77BEF9",
    hoverIconColor: "#23649A",
    backgroundColor: "#23649A",
    iconBackgroundColor: "#77BEF9",
    height: "200px",
    fontColor: "#fff",
    link: "/dashboard/Offerslist",
  },
  {
    title: "Shelters",
    description: "Find animal shelters near your location",
    icon: home,
    hoverBackgroundColor: "#7FAE70",
    hoverIconColor: "#408D27",
    backgroundColor: "#408D27",
    iconBackgroundColor: "#7FAE70",
    height: "200px",
    fontColor: "#fff",
    link: "",
  },
  {
    title: "Social Organization",
    description: "Find social organizations near your location",
    icon: home,
    hoverBackgroundColor: "#23649A",
    hoverIconColor: "#77BEF9",
    backgroundColor: "#77BEF9",
    iconBackgroundColor: "#23649A",
    height: "200px",
    fontColor: "#fff",
    link: "",
  },
];

export default modules;
